### ISSUE TITLE
Help setting up the maxify scanner

### ISSUE THREAD

**Issue by Zulan** [mhelff/maxify-smbv1#1]
Hi Martin,

thanks for providing this package. I am wondering if you could help me out getting this working on the Maxify MB5150.

I have setup the container in podman with a dedicated ip in a separate macvlan network.

On a separate Linux system, I can access the share with smbclient or thunar (anonymously).

However, with the Canon Quick Utility Toolbox, entering the shared folder name "\\192.168.33\consume". I always get the error "Failed to connect to the folder. Check the settings.".

I also cannot really connect to the share on the windows system, but I assume that is due to the old version.

I've update the Canon firmware to 1.160. All devices are in the same local network. I couldn't get the port forwarded version to work, I guess smb needs some more ports, but I want to run a seperate proper smb installation on the host anyway.

Do you have any recommendation what else to try?

**Comment by mhelff** [comment]
Your IP (192.168.33) looks incomplete?
I never used podman, but if you can access the share from a other system it looks like you might have a typo.

**Comment by Zulan** [comment]
> Your IP (192.168.33) looks incomplete? I never used podman, but if you can access the share from a other system it looks like you might have a typo.

Apologies, the typo was just in the github issue, what I actually use is `\\192.168.0.33\consume`. I just double checked in case I messed it up yesterday.

I was just wondering if there's anything else I need to set there (domain/user, password, pin).

**Comment by Zulan** [comment]
It turns out the share's root folder was not writable by uid 1000 as per the outside permissions. That caused the diffuse error.

Sorry about the trouble.

**Comment by mhelff** [comment]
Nice to hear everything is working now!
